"""Module 4 — Telegram Reporter.

Formats the daily screener output (and the weekly backtest summary) into a
Telegram message and sends it via the Bot API. No third-party SDK required —
just an HTTPS POST.
"""
from __future__ import annotations

import logging
from datetime import datetime

import pandas as pd

from . import backtester, config
from .screener import Signal

logger = logging.getLogger("quant_screener.telegram_bot")

DIVIDER = "━━━━━━━━━━━━━━━"
_ID_MONTHS = [
    "Januari", "Februari", "Maret", "April", "Mei", "Juni",
    "Juli", "Agustus", "September", "Oktober", "November", "Desember",
]

# Strategy key -> (emoji, heading) used to render report sections.
_SECTIONS = {
    "volume_anomaly": ("🔥", "VOLUME ANOMALY"),
    "breakout_52w": ("📈", "BREAKOUT 52W HIGH"),
    "rsi_oversold": ("📉", "RSI OVERSOLD (Potential Bounce)"),
}


def _rupiah(value: float) -> str:
    """Format a price the Indonesian way: Rp 9.450 (dot as thousands sep)."""
    return "Rp " + f"{value:,.0f}".replace(",", ".")


def _id_date(dt: datetime | None = None) -> str:
    dt = dt or datetime.now()
    return f"{dt.day} {_ID_MONTHS[dt.month - 1]} {dt.year}"


def _format_signal_line(sig: Signal) -> str:
    if sig.strategy == "volume_anomaly":
        rsi = f" | +RSI {sig.rsi:.0f}" if sig.rsi is not None else ""
        vol = f" | Vol {sig.vol_ratio}x" if sig.vol_ratio is not None else ""
        return f"- {sig.ticker} — {_rupiah(sig.close)}{vol}{rsi}"
    if sig.strategy == "breakout_52w":
        vol = f" | Vol {sig.vol_ratio}x" if sig.vol_ratio is not None else ""
        return f"- {sig.ticker} — {_rupiah(sig.close)}{vol}"
    if sig.strategy == "rsi_oversold":
        rsi = f" | RSI {sig.rsi:.0f}" if sig.rsi is not None else ""
        ma = " | Above MA200 ✅" if sig.above_ma200 else ""
        return f"- {sig.ticker} — {_rupiah(sig.close)}{rsi}{ma}"
    return f"- {sig.ticker} — {_rupiah(sig.close)}"


def format_daily_report(
    grouped: dict[str, list[Signal]], dt: datetime | None = None
) -> str:
    """Build the daily screener Telegram message."""
    lines = [f"📊 *IHSG SCREENER — {_id_date(dt)}*", DIVIDER, ""]

    any_signal = False
    for key, (emoji, title) in _SECTIONS.items():
        sigs = grouped.get(key, [])
        lines.append(f"{emoji} *{title}*")
        if sigs:
            any_signal = True
            lines.extend(_format_signal_line(s) for s in sigs)
        else:
            lines.append("- (tidak ada sinyal hari ini)")
        lines.append("")

    if not any_signal:
        lines.append("_Tidak ada sinyal yang trigger pada sesi hari ini._")
        lines.append("")

    lines.append("⚠️ *Disclaimer: Ini bukan rekomendasi investasi*")
    lines.append(DIVIDER)
    lines.append("🤖 Auto-generated by QuantScreener v1.0")
    return "\n".join(lines)


def format_weekly_summary(
    results: pd.DataFrame, dt: datetime | None = None
) -> str:
    """Build the weekly backtest performance summary message."""
    lines = [f"🗓️ *WEEKLY BACKTEST SUMMARY — {_id_date(dt)}*", DIVIDER, ""]

    if results is None or results.empty:
        lines.append("_Belum ada hasil backtest._")
    else:
        for key, (emoji, title) in _SECTIONS.items():
            sub = results[results["strategy"] == key]
            sub = sub[sub["num_trades"] > 0]
            lines.append(f"{emoji} *{title}*")
            if sub.empty:
                lines.append("- (tidak ada trade)")
            else:
                avg_wr = sub["win_rate_pct"].mean()
                avg_ret = sub["total_return_pct"].mean()
                lines.append(f"- Avg win rate: {avg_wr:.1f}% | Avg return: {avg_ret:.1f}%")
                top = sub.sort_values("win_rate_pct", ascending=False).head(3)
                for _, r in top.iterrows():
                    lines.append(
                        f"  • {r['ticker']}: WR {r['win_rate_pct']:.0f}% | "
                        f"Ret {r['total_return_pct']:.0f}% | "
                        f"Sharpe {r['sharpe']:.2f} | {int(r['num_trades'])} trades"
                    )
            lines.append("")

        best = backtester.best_strategy(results)
        if best:
            label = _SECTIONS.get(best[0], (None, best[0]))[1]
            lines.append(f"🏆 *Best strategy:* {label} (avg WR {best[1]:.1f}%)")
            lines.append("")

    lines.append("⚠️ *Disclaimer: Ini bukan rekomendasi investasi*")
    lines.append(DIVIDER)
    lines.append("🤖 Auto-generated by QuantScreener v1.0")
    return "\n".join(lines)


def send_message(text: str) -> bool:
    """Send a Markdown message to the configured chat. Returns success flag."""
    if config.TELEGRAM_TOKEN in ("", "your_token") or config.TELEGRAM_CHAT_ID in (
        "",
        "your_chat_id",
    ):
        logger.error("Telegram token/chat_id not configured — printing instead:\n%s", text)
        return False

    import httpx

    url = f"https://api.telegram.org/bot{config.TELEGRAM_TOKEN}/sendMessage"
    payload = {
        "chat_id": config.TELEGRAM_CHAT_ID,
        "text": text,
        "parse_mode": "Markdown",
        "disable_web_page_preview": True,
    }
    for attempt in range(1, 4):
        try:
            resp = httpx.post(url, json=payload, timeout=20)
            if resp.status_code == 200:
                logger.info("Telegram message sent (%d chars)", len(text))
                return True
            logger.warning("Telegram API %s: %s", resp.status_code, resp.text[:300])
        except Exception as exc:
            logger.warning("Telegram send attempt %d failed: %s", attempt, exc)
    return False


def send_daily_report(grouped: dict[str, list[Signal]]) -> bool:
    return send_message(format_daily_report(grouped))


def send_weekly_summary(results: pd.DataFrame) -> bool:
    return send_message(format_weekly_summary(results))


if __name__ == "__main__":  # preview the formatting without sending
    logging.basicConfig(level=logging.INFO)
    demo = {
        "volume_anomaly": [
            Signal("BBCA", "volume_anomaly", 9450, vol_ratio=3.2, rsi=58),
            Signal("TLKM", "volume_anomaly", 3200, vol_ratio=2.8, rsi=61),
        ],
        "breakout_52w": [
            Signal("ASII", "breakout_52w", 5500, vol_ratio=1.9),
            Signal("UNVR", "breakout_52w", 4100, vol_ratio=1.6),
        ],
        "rsi_oversold": [
            Signal("INDF", "rsi_oversold", 6750, rsi=32, above_ma200=True),
        ],
    }
    print(format_daily_report(demo))
